###
GET http://localhost:8080/api/v1/content

###
GET http://localhost:8080/api/v1/content/3

### Create new content
POST http://localhost:8080/api/v1/content
Content-Type: application/json

{
  "id": 3,
  "description": "Third Content",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2023-05-10T15:31:53.8756767",
  "dateUpdated": null,
  "url": ""
}

