###
GET http://localhost:8080/api/v1/trips

###
GET http://localhost:8080/api/v1/trips/1

### Create new content
POST http://localhost:8080/api/v1/trips
Content-Type: application/json

{
  "description": "Trip to Bali",
  "status": "COMPLETED",
  "trip_type": "BEACH",
  "distance": 100,
  "price": 100.0,
  "start_date": null,
  "end_date": null,
  "url": null
}

### Update existing content
PUT http://localhost:8080/api/v1/trips/1
Content-Type: application/json

{
  "id": 1,
  "description": "Trip to the beach2",
  "status": "COMPLETED",
  "trip_type": "WORK",
  "distance": 100,
  "price": 100.0,
  "start_date": null,
  "end_date": null,
  "url": null
}

### Delete existing content
DELETE http://localhost:8080/api/v1/trips/3

